version: "1.0"
info:
  scaffold: XSLTTransform
  model: int-scaffold
services:
- serviceName: edge.luis_sandpit.integrations:XSLTTransform
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.luis_sandpit.integrations:DataTransformation
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
