version: "1.0"
info:
  scaffold: EdgeLuis_Sandpit
  model: int-scaffold
services:
- serviceName: edge.luis_sandpit.integrations:XSLTTransform
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
- serviceName: edge.luis_sandpit.javaservices.Default:MyJavaService
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
