version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.luis_sandpit.integrations:GetCurrentDate
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
- serviceName: edge.luis_sandpit.integrations:XSLTTransform
  packages:
  - name: EdgeLuis_Sandpit
    version: "1.0"
